# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# # Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

languages:
  en: English
  fr: Français
  es: Español
  it: Italiano
  pl: Polski
  ro: Română
  he: עברית
  hi: हिन्दी

default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

defaults:
  -
    values:
      direction: "ltr"
      title: STAY SAFE DURING THE PANDEMIC

      section1-title: First of all, don't panic
      section1-1: Avoid crowds and large gatherings. Make sure to keep physical distance from others.
      section1-2: Wash your hands regularly for 20 seconds. Use soap, or hand sanitiser whenever possible.
      section1-3: Always use your elbow to cover your mouth when you cough or sneeze. Avoid touching your face.

      section2-title: "Plan, prepare, #stayhome"
      section2-1: Plan ahead and ask others for help to ensure that you can stay at home as much as possible.
      section2-2: If you have cough or high temperature, stay isolated for 14 days from when your symptoms started.
      section2-3: Prepare a room or shelter for those over 70 where they can stay isolated (with a carer, if necessary).

#      section3-title: "Whether at home or not, stay safe"
#      section3-1: Wear a mask. Learn how you can make one here. No sewing required.
#      section3-2: Always use your elbow to cover your mouth when you cough or sneeze. Avoid touching your face.
#      section3-3: Share these tips with your family and friends. Together we can put an end to the outbreak!

      section4-title: "Follow trusted sources"
      badAdvice: Bad advice is as dangerous as the coronavirus itself. Follow trusted sources. Use this map to find yours.
#      Always check with more than one source. Are all or most sources saying the same thing?

      section5-title: "Share these tips"

      learnMore: LEARN MORE

      learnMoreAt: Learn more at

      metaDescription: Learn the bare minimum you need to stay safe. Find local sources of information. Join our campaign to limit the spread of the coronavirus.

      missAnything: Did we miss anything?
      letUsKnow: Let us know.

      follow: Follow

      disclaimer: "Disclaimer: The content of this website does not constitute medical advice. The information provided above is meant as a suggestion for concerned individuals to follow a loose set of guidelines based on best practices and anecdotal evidence to protect themselves and their loved ones. There is no guarantee or scientific evidence that following the mentioned guidelines will lead to a reduction in new infections or even stop the COVID-19 epidemic. There is also no guarantee that following these guidelines will reduce the risk of getting infected with SARS-CoV-2 or any other viral or bacterial contagion. All information provided on this website is given with the best intent and will to provide factual information. In no event shall the website operators be held liable for any claim, damages, or other liabilities. If you have concerns or comments about the information provided on this website, please write to contact@stayhomecampaign.org."